### PR TITLE
✨feat(content_dev): Added content development page

### PR DESCRIPTION
**Pull request by Vickynjoroge**
# Description

This pull request introduces the content development page, including the creation of the HTML file with its structural elements and the corresponding CSS for styling.
The content development page is now fully developed and ready for integration.

I worked on this PR @Tugi-Ngunjiri 

Fixes #1 #12 #75 

## Type of change

Please delete options that are not relevant.
- [x] New feature (non-breaking change which adds functionality)

## Screenshot (optional)
**Desktop**
Screenshot 2023-10-16 222843

**Tablet**
Screenshot 2023-10-16 222741

**Mobile**
Screenshot 2023-10-16 222808

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by Vickynjoroge** [comment]
@JAPHETHNYARANGA 
This PR  is ready for review

**Comment by Vickynjoroge** [comment]
@JAPHETHNYARANGA 
This PR  is ready for review

**Comment by Vickynjoroge** [comment]
@JAPHETHNYARANGA 
This PR  is ready for review

**Comment by JAPHETHNYARANGA** [comment]
Good attempt closing this pr as it is already done, please pick another issue

**Pull request closed without merging**
