### PR TITLE
:sparkles::art::lipstick: feat: created a website header and styled it 

### PR DESCRIPTION
**Pull request by MorganJason420**
# Description
I first created the div container for the header.I then created a div container for the logo and added the logo image inside the div. 
I then created a div which contains the dropdown selection.Lastly i added a button and styled each respectively in the css file.
#1 

## Type of change

##screenshot
(
image
)

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by paulkahura — CHANGES_REQUESTED** [review]
Kindly add screenshots for review

**Comment by MorganJason420** [comment]
I have added the screenshot

**Review by MorganJason420 — COMMENTED** [review]
I have added the screenshot

**Comment by paulkahura** [comment]
just take a screenshot of the page and `ctr + v` on the 'SCREENSHOT (OPTIONAL)` section

**Comment by MorganJason420** [comment]
I have corrected thatt.Thank youu

**Pull request closed without merging**
