### PR TITLE
✨ feat: Added website header #1

### PR DESCRIPTION
**Pull request by Vickynjoroge**
# Description

Added a website header also included a logo, navigation list with one of it (Solutions) has dropdown option and a contact us button.
It is resposive to the different width.

Fixes #1  

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)

## Screenshot (optional)
**Desktop**
Screenshot 2023-10-05 111413

**Tablet**
Screenshot 2023-10-05 111437
Screenshot 2023-10-05 111500

**Mobile**
Screenshot 2023-10-05 111437
Screenshot 2023-10-05 111524

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] When rendered the component is pixel-perfect compared to the design above.
- [x] The header adapts naturally to different screen widths

### CODE REVIEW

**Comment by Vickynjoroge** [comment]
I worked on this with @Tugi-Ngunjiri

**Comment by Vickynjoroge** [comment]
@paulkahura 
 I have updated the issue and its ready for review

**Comment by paulkahura** [comment]
> @paulkahura I have updated the issue and its ready for review

Kindly add the new screenshots

**Comment by Vickynjoroge** [comment]
@paulkahura 
I have updated the screenshots as requested

**Comment by Vickynjoroge** [comment]
@JAPHETHNYARANGA 
I have updated this PR and its ready for review

**Review by JAPHETHNYARANGA — COMMENTED** [review]
closing as this is done

**Review by JAPHETHNYARANGA — COMMENTED** [review]
closing as this is done. please pick another issue, thank you

**Pull request closed without merging**
