### PR TITLE
Convresational learning page

### LINKED ISSUE #79: 💄 🎨 Create the conversational learning page hero section
#  Create the conversational learning page hero section.

---
NB: This issue depends on #10 and #1

---

Quick links: [Summary](#summary) | [Description](#description) | [Technical-Analysis](#Technical-Analysis) | [Acceptance-Criteria](#Acceptance-Criteria)

---

### Summary

As a user, I want a nice hero section on the conversational learning page that captures my attention and introduces the page content. I want a good experience on the web and phone.

Design:
conv-learning

Link to full design:

```
https://xd.adobe.com/view/b98caf27-6549-49e5-8ed8-c5234788df61-ecdf/screen/cc35e19a-24f2-42ce-8803-ee2942839528/
```
 
### Technical Analysis

This feature can be found in src/features/pages inside ` conversational-learning-page.html`.

### Acceptance Criteria

1. When rendered the component is pixel-perfect compared to the design above.
5. The design is responsive for screen, tablet and phone

### PR DESCRIPTION
**Pull request by winniegithubrit**
# Description
I have created the conversational learning page  

Fixes #79  (issue) 
## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)

## Screenshot (optional)
Screenshot from 2023-10-05 15-12-07

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by JAPHETHNYARANGA — CHANGES_REQUESTED** [review]
Good attempt, but its always recommended to just push the file required for the issue to prevent merging and changing the other files also already done. This is important in open source projects. Good attempt  though.

**Review by JAPHETHNYARANGA — COMMENTED** [review]
Good work but your branch has conflicts. Main causes of conflicts is pushing other files not required. For example this, just work  on the conv learning page files then a link may be required in index to test, after you are done remove it and return all files not needed for the issue in the state they are in as main. I hope this helps.

**Comment by winniegithubrit** [comment]
Thank you  I'll correct that

**Comment by JAPHETHNYARANGA** [comment]
Good work , Make sure  to only change the require files,you can use github desktop to solve the conflicts.

**Pull request closed without merging**
