### PR TITLE
News page

### LINKED ISSUE #7: 🎨 Create Home Page News Section Component
#  🎨 Create the Home Page News Section Component
---

Quick links: [Summary](#summary) | [Description](#description) | [Technical-Analysis](#Technical-Analysis) | [Acceptance-Criteria](#Acceptance-Criteria)

---

### Summary

As a user, I want a section that displays all news- items(blogs) that I have on my homepage.

NewsPage

Please take note of all the design features

#### Link to full design:
```
https://xd.adobe.com/view/b98caf27-6549-49e5-8ed8-c5234788df61-ecdf/screen/cc35e19a-24f2-42ce-8803-ee2942839528/
```

### Technical Analysis

This component will be created in `index.html`

### Acceptance Criteria

- [ ] When rendered the section is pixel-perfect compared to the design above.
- [ ] The section is aligned using CSS grid
- [ ] The design is responsive for screen, tablet and phone

### PR DESCRIPTION
**Pull request by Ngaremaina**
# Description
Adding the news page and styling the news page 

Issue #7 .

Fixes #7 

Tags
@danielsdgg @afrikhana

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)
- [x] This change requires a documentation update

## Screenshot (optional)
Screenshot from 2023-10-04 15-10-29
Screenshot from 2023-10-04 15-10-18
Screenshot from 2023-10-04 15-10-07

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [x] The page runs on the browser
- [x] The page displays the components as expected

**Test Configuration**: (optional)

- Firmware version:
- Hardware:
- Toolchain:
- SDK:

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by JAPHETHNYARANGA — CHANGES_REQUESTED** [review]
check the text sizes and their weights, the horizontal line is not end to end as per the design, and  how did the screen shot work with the styles attached only.Screen shot looks good but i cant see the styles.Please check on this. Thanks.

**Comment by Ngaremaina** [comment]
# Description
Updated the font weights and the horizontal line

Please include a summary of the changes and the related issue. Please also include relevant motivation and context. List any dependencies that are required for this change.

Issue #7 .

Fixes #7 

Tags
@danielsdgg @afrikhana

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)
- [x] This change requires a documentation update

## Screenshot (optional)
Desktop
Tablet
Mobile View

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [x] The page runs on the browser
- [x] The page displays the components as expected

**Test Configuration**: (optional)

- Firmware version:
- Hardware:
- Toolchain:
- SDK:

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

**Comment by Ngaremaina** [comment]
Please check now and let me know.

**Comment by JAPHETHNYARANGA** [comment]
THis is good work, but always remember to just push the required files. For the specific issue

**Review by JAPHETHNYARANGA — APPROVED** [review]

**Pull request merged**
