### PR TITLE
💄 create landing page #2

### LINKED ISSUE #2: 🎨  Create the home landing page
#  Create the Home Landing page 
---
NB: This issue is dependent on #1

---
Quick links: [Summary](#summary) | [Description](#description) | [Technical-Analysis](#Technical-Analysis) | [Acceptance-Criteria](#Acceptance-Criteria)

---

### Summary

As a user, I want a nice hero section on the home page that captures my attention and introduces the page content. I want a good experience on the web and phone. Use the header created in #1.

### Description

Design:
HomeLandingPage

Link to full design:

```
https://xd.adobe.com/view/b98caf27-6549-49e5-8ed8-c5234788df61-ecdf/screen/cc35e19a-24f2-42ce-8803-ee2942839528
```

### Assets.
Logo URL
```
https://res.cloudinary.com/dyl3rncv3/image/upload/v1695970671/elewa-education-website/Shared/elewa-logo_eocvkz.png
```

Right Arrow URL
```
https://res.cloudinary.com/dyl3rncv3/image/upload/v1695972080/elewa-education-website/Shared/toRightArrow_tlcdnk.svg
```
### Technical Analysis

This feature can be found in `index.html`.

### Acceptance Criteria

1. When rendered the hero is pixel-perfect compared to the design above.
4. The design is responsive for screen, tablet and phone

### PR DESCRIPTION
**Pull request by Ase020**
# Description

Created the navbar and landing page hero section

Fixes #2 
## Type of change

Please delete options that are not relevant.

- [ x] New feature (non-breaking change which adds functionality)

## Screenshot (optional)

Screenshot 2023-09-28 115612

## Checklist

- [ x] My code follows the style guidelines of this project
- [ x] I have performed a self-review of my code
- [ x] I have commented my code, particularly in hard-to-understand areas
- [ x] My changes generate no new warnings

### CODE REVIEW

**Review by JAPHETHNYARANGA — COMMENTED** [review]
Please make the page responsive using Media Query and attach screen shots of web and mobile views

**Review by JAPHETHNYARANGA — COMMENTED** [review]
you are almost there, use media queries for responsiveness

**Comment by Ase020** [comment]
Okay this is noted.

**Comment by Ase020** [comment]
> you are almost there, use media queries for responsiveness

This is noted though there are no mobile designs @JAPHETHNYARANGA

**Review by Ase020 — COMMENTED** [review]
Responsive design done.

**Comment by JAPHETHNYARANGA** [comment]
closing as this is done, please pick another issue

**Pull request closed without merging**
