### PR TITLE
:memo: Conversational learning page #79

### PR DESCRIPTION
**Pull request by SKaranjaN**
# Description

Created the conversational page that is also mobile responsive.

Reference the issue related to this PR as shown below. Every issue has it's own number you can find the issue numbers #79  (https://github.com/italanta/elewa-website-html/issues/79).

image
image

- [x] New feature (non-breaking change which adds functionality)
- [x] This change requires a documentation update

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

### CODE REVIEW

**Review by JAPHETHNYARANGA — COMMENTED** [review]
this issue has already been merged with another pr

**Review by JAPHETHNYARANGA — CHANGES_REQUESTED** [review]
Very good work, please resolve the conflicts in the style file

**Comment by SKaranjaN** [comment]
> Very good work, please resolve the conflicts in the style file

The conflicts have been resolved.

**Comment by JAPHETHNYARANGA** [comment]
This is very good work. I would use box-sizing:border-box then use paddings instead of using margins as first option.Closing the pr because the issue is merged allready. But very good work

**Pull request closed without merging**
