### PR TITLE
:memo: Create consultancy page

### PR DESCRIPTION
**Pull request by LimisiMike**
# Description

Created a Consultancy Page where I can add the different sections of my consultancy page.

Reference the issue related to this PR as shown below. 
(https://github.com/italanta/elewa-website-html/issues/11).

Fixes # 11 

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

### CODE REVIEW

**Review by JAPHETHNYARANGA — COMMENTED** [review]
Issues mixed. work on just one issue per pull request

**Review by JAPHETHNYARANGA — APPROVED** [review]

**Review by JAPHETHNYARANGA — CHANGES_REQUESTED** [review]
Sorry for the previous approval , consultancy page was already created

**Comment by LimisiMike** [comment]
Please check the changes.

**Comment by JAPHETHNYARANGA** [comment]
closing pr as issue is closed

**Pull request closed without merging**
