### PR TITLE
Home landing page

### LINKED ISSUE #2: 🎨  Create the home landing page
#  Create the Home Landing page 
---
NB: This issue is dependent on #1

---
Quick links: [Summary](#summary) | [Description](#description) | [Technical-Analysis](#Technical-Analysis) | [Acceptance-Criteria](#Acceptance-Criteria)

---

### Summary

As a user, I want a nice hero section on the home page that captures my attention and introduces the page content. I want a good experience on the web and phone. Use the header created in #1.

### Description

Design:
HomeLandingPage

Link to full design:

```
https://xd.adobe.com/view/b98caf27-6549-49e5-8ed8-c5234788df61-ecdf/screen/cc35e19a-24f2-42ce-8803-ee2942839528
```

### Assets.
Logo URL
```
https://res.cloudinary.com/dyl3rncv3/image/upload/v1695970671/elewa-education-website/Shared/elewa-logo_eocvkz.png
```

Right Arrow URL
```
https://res.cloudinary.com/dyl3rncv3/image/upload/v1695972080/elewa-education-website/Shared/toRightArrow_tlcdnk.svg
```
### Technical Analysis

This feature can be found in `index.html`.

### Acceptance Criteria

1. When rendered the hero is pixel-perfect compared to the design above.
4. The design is responsive for screen, tablet and phone

### PR DESCRIPTION
**Pull request by afrikhana**
# Description
Updated the responsiveness of the page to response depending on any screen size

Fixes # (issue) - *Example*: Fixes #2 

## Screenshot (optional)
home-landingpg-lp
##smaller laptop screen size
home-landing-pd-smlp
smaller-home-landing-pg

##tablet resp
tablet-home-landing-page

##mobile resp
monile-home-landing-page

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works

### CODE REVIEW

**Review by JAPHETHNYARANGA — CHANGES_REQUESTED** [review]
Please check the color schema, please check the dimensions of the items from the end or start of screen and use the exact dimensions  on the objects. Also try looking into the conflicts . prefarably use Github desktop

**Comment by afrikhana** [comment]
Hallo Sr. I made the changes and updated the web page but am having issues with my git hub conflicts so Sr. Lemmy agreed to help me tmrw.

**Comment by afrikhana** [comment]
> Please check the color schema, please check the dimensions of the items from the end or start of screen and use the exact dimensions on the objects. Also try looking into the conflicts . prefarably use Github desktop

Addressed all issues....

**Review by JAPHETHNYARANGA — COMMENTED** [review]
Good work but closing as this is done, please pick another issue

**Pull request closed without merging**
