### PR TITLE
Create website header

### PR DESCRIPTION
**Pull request by Pychangeric**
On this part I have been working on the header and also triying to work on the button which have been a bit unresponsive.
 
Please include a summary of the changes and the related issue. Please also include relevant motivation and context. List any dependencies that are required for this change.

Reference the issue related to this PR as shown below. Every issue has it's own number you can find the issue numbers [here](https://github.com/italanta/italanta-apps/issues).

Fixes #1  (issue) - *Example*: Fixes #10, #20 NOTE: GitHub issue numbers should be prefixed with **#** to aid with issue tracking.

## Type of change

Please delete options that are not relevant.

- [x ] New feature (non-breaking change which adds functionality)
- [x ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Screenshot (optional)
header

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

**Test Configuration**: (optional)

- Firmware version:
- Hardware:
- Toolchain:
- SDK:

## Checklist

- [ x] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [x ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by JAPHETHNYARANGA — COMMENTED** [review]
closing as this is done

**Comment by Pychangeric** [comment]
Thanks for the comment is there anyting an supposed to add.

**Comment by JAPHETHNYARANGA** [comment]
Morning sir, just get another issue and do it, one that isn't done

**Comment by Pychangeric** [comment]
thanks lemme work on a
nother

**Pull request closed without merging**
