### PR TITLE
:lipstick: create an empty content development html file

### LINKED ISSUE #12: ✨📝 Create Content-Development Page HTML file
## User stories

As a Developer I need a Page HTML file where I can add the different sections of my content development page.

---

Quick links: [Summary](#summary) | [Description](#description) | [Template](#template) | [Example](#example) | [Resources](#resources)

---

### Description

As a Developer I need a Page HTML file where I can add the different sections of my content development page.

### Technical Analysis

The file should be placed in the library `src/features/pages`. The name of the file is `content-development-page.html`.

### Acceptance Criteria

- [ ] The code is isolated to the `libs/features/pages` unless a justified reason is specified.
- [ ] A separate commit is used for each small change
- [ ] The commits and PR are well formatted/use proper documentation

### PR DESCRIPTION
**Pull request by augasha04**
# Description
- created directory features and pages inside the source directory.
- created an empty `content-development.html` file inside `src/features/pages`
Fixes #12 

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by LemmyMwaura — DISMISSED** [review]

**Review by Beulah-Matt — APPROVED** [review]
Good job following the PR formatting instructions.

**Comment by augasha04** [comment]
Thank you, Beulah.

**Review by Beulah-Matt — COMMENTED** [review]
I was expecting a file with the usual html markup of a head tag and empty body. However, you want to merge an empty file and have worked on more than one issue. Check on this next time.

**Comment by augasha04** [comment]
Thank you for the update and correction, I will check that in the next
issues. I guess I was just confused about the issues, but in the other
issues that I have done, I have added some html basic markups.

Thank you, Regards
A.M.K

**Pull request closed without merging**
